from .login import *
from .forgotpassword import *
from .users import *
from .fppages import *
from .page import *
from .dashboard import *
from .settings import *
from .widgets import *
from .mediaupload import *
from .menus import *
