# Generated by Django 2.2.1 on 2019-05-23 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagemeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.TextField(default='')),
                ('meta_value', models.TextField(default='')),
                ('page_id', models.PositiveSmallIntegerField(default=0)),
                ('page_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('page_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=250)),
                ('page_slug', models.TextField(default='')),
                ('page_banner', models.TextField(default='')),
                ('page_excerpt', models.TextField(default='')),
                ('page_description', models.TextField(default='')),
                ('page_author', models.PositiveSmallIntegerField(default=0)),
                ('page_parent', models.PositiveSmallIntegerField(default=0)),
                ('page_subheading', models.CharField(default='', max_length=250)),
                ('page_status', models.CharField(default='publish', max_length=250)),
                ('page_visible', models.CharField(default='public', max_length=250)),
                ('page_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('page_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
    ]
