# Generated by Django 2.2.1 on 2019-05-24 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20190524_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.TextField(default='')),
                ('image_url', models.TextField(default='')),
                ('page_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('page_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
    ]
