# Generated by Django 2.2.1 on 2019-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page_access_level',
            field=models.CharField(default='[]', max_length=250),
        ),
    ]
