# Generated by Django 2.2.1 on 2019-05-29 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_pages_page_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.TextField(default='')),
                ('option_value', models.TextField(default='')),
                ('page_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('page_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
    ]
