# Generated by Django 2.2.1 on 2019-05-30 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=250)),
                ('package_price', models.TextField(default='')),
                ('package_type', models.TextField(default='')),
                ('package_details', models.TextField(default='')),
                ('package_status', models.CharField(default='', max_length=250)),
                ('Package_for', models.CharField(default='', max_length=250)),
                ('package_vat', models.CharField(default='', max_length=250)),
                ('package_time', models.CharField(default='', max_length=250)),
                ('package_vatamt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('page_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
    ]
