# Generated by Django 2.2.1 on 2019-05-30 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='page_updated',
            new_name='package_created',
        ),
        migrations.AddField(
            model_name='package',
            name='package_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_vatamt',
            field=models.CharField(default='', max_length=250),
        ),
    ]
