# Generated by Django 2.2.1 on 2019-05-30 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20190530_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(default='', max_length=250)),
                ('property_slug', models.CharField(default='', max_length=250)),
                ('property_excerpt', models.TextField(default='')),
                ('property_description', models.TextField(default='')),
                ('property_price', models.PositiveSmallIntegerField(default=0)),
                ('property_phone', models.CharField(default='', max_length=250)),
                ('property_label', models.CharField(default='', max_length=250)),
                ('property_image', models.CharField(default='', max_length=250)),
                ('property_fulladdress', models.TextField(default='')),
                ('property_city', models.CharField(default='', max_length=250)),
                ('property_nearest', models.CharField(default='', max_length=250)),
                ('property_state', models.CharField(default='', max_length=250)),
                ('property_zipcode', models.CharField(default='', max_length=250)),
                ('property_country', models.CharField(default='', max_length=250)),
                ('property_others', models.TextField(default='')),
                ('author_id', models.PositiveSmallIntegerField(default=0)),
                ('property_category', models.PositiveSmallIntegerField(default=0)),
                ('property_type', models.CharField(default='', max_length=250)),
                ('property_status', models.CharField(default='publish', max_length=250)),
                ('meta_title', models.CharField(default='', max_length=250)),
                ('meta_keyword', models.CharField(default='', max_length=250)),
                ('meta_description', models.CharField(default='', max_length=250)),
                ('property_lat', models.CharField(default='0', max_length=250)),
                ('property_lng', models.CharField(default='0', max_length=250)),
                ('property_brochure', models.CharField(default='', max_length=250)),
                ('property_epc', models.CharField(default='', max_length=250)),
                ('property_bedroom', models.CharField(default='', max_length=250)),
                ('property_furnish', models.CharField(default='', max_length=250)),
                ('property_guestroom', models.CharField(default='', max_length=250)),
                ('property_bath', models.CharField(default='', max_length=250)),
                ('property_room', models.CharField(default='', max_length=250)),
                ('property_visible_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('property_hide_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('property_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('property_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Package_for',
            new_name='package_for',
        ),
    ]
