# Generated by Django 2.2.1 on 2019-05-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_auto_20190530_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stipe_plan_id',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='package',
            name='stipe_product_id',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='property',
            name='property_facing',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='property',
            name='property_floor',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='property',
            name='property_garden',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='property',
            name='property_owner',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='property',
            name='property_size',
            field=models.CharField(default='', max_length=250),
        ),
    ]
