# Generated by Django 2.2.1 on 2019-06-17 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_auto_20190531_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=250)),
                ('menu_slug', models.CharField(max_length=250)),
                ('menu_content', models.TextField(default='')),
                ('menu_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('menu_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
    ]
