# Generated by Django 2.2.1 on 2019-06-21 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=250)),
                ('from_name', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(default='')),
                ('success_message', models.TextField(default='')),
                ('error_message', models.TextField(default='')),
                ('page_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('page_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_content', models.CharField(max_length=5000)),
                ('services_photo', models.TextField(default='')),
                ('services_name', models.CharField(max_length=100)),
                ('testimonial_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
    ]
