# Generated by Django 2.2.1 on 2019-06-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_emails_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='testimonial_created',
            new_name='services_created',
        ),
    ]
