# Generated by Django 2.2.1 on 2019-06-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_auto_20190621_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='email_key',
            field=models.TextField(default=''),
        ),
    ]
