# Generated by Django 2.2.1 on 2019-06-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_emails_email_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
