# Generated by Django 2.2.3 on 2019-07-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_auto_20190708_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemeta',
            name='page_id',
            field=models.IntegerField(default=0),
        ),
    ]
