# Generated by Django 2.2.3 on 2019-07-09 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_auto_20190708_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.TextField(default='')),
                ('meta_value', models.TextField(default='')),
                ('user_id', models.IntegerField(default=0)),
                ('page_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('page_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
    ]
